"""Update wards.name from "Ward N" to real MCD/NDMC/Cantt ward names

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-21
"""

from alembic import op

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None

# Complete MCD ward number → real name mapping (numeric wards 1-272)
WARD_NAMES: dict[int, str] = {
    1: "NARELA",
    2: "BANKNER",
    3: "ALIPUR",
    4: "BAKHTAWAR PUR",
    5: "BHALASWA JAHAGIR PUR",
    6: "MUKUND PUR",
    7: "BURARI",
    8: "JHARODA",
    9: "MALKAGANJ",
    10: "TIMAR PUR",
    11: "MUKHERJEE NAGAR",
    12: "G.T.B. NAGAR",
    13: "DHIR PUR",
    14: "ADARSH NAGAR",
    15: "SARAI PIPAL THALA",
    16: "JAHANGIRPURI-I",
    17: "SAMAYPUR BADLI",
    18: "LIBAS PUR",
    19: "BHALSWA",
    20: "JAHANGIR PURI-II",
    21: "ROHINI",
    22: "RITHALA",
    23: "BUDH VIHAR",
    24: "VIJAY VIHAR",
    25: "POOTH KALAN",
    26: "SAHIBABAD DAULAT PUR",
    27: "BEGUMPUR",
    28: "BAWANA",
    29: "KARALA",
    30: "MUNDAKA",
    31: "NANGLOI JAT WEST",
    32: "NILOTHI",
    33: "PREM NAGAR",
    34: "NITHARI",
    35: "KIRARI SULEMAN NAGAR",
    36: "PRATAP VIHAR",
    37: "SULTANPURI EAST",
    38: "MANGOL PURI NORTH",
    39: "SULTANPUR MAJRA",
    40: "SULTANPURI SOUTH",
    41: "GURU HARKISHAN NAGAR",
    42: "PERAGHARHI",
    43: "NANGLOI EAST",
    44: "QUAMMRUDDIN NAGAR",
    45: "ROHINI SOUTH",
    46: "MANGOLPURI EAST",
    47: "MANGOLPURI",
    48: "MANGOLPURI WEST",
    49: "ROHINI NORTH",
    50: "ROHINI CENTRAL",
    51: "ROHINI EAST",
    52: "NAHARPUR",
    53: "PITAMPURA SOUTH",
    54: "PITAMPURA NORTH",
    55: "SHALIMAR BAGH NORTH",
    56: "SHALIMAR BAGH SOUTH",
    57: "PASCHIM VIHAR SOUTH",
    58: "PASCHIM VIHAR NORTH",
    59: "RANI BAGH",
    60: "SARASWATI VIHAR",
    61: "TRI NAGAR",
    62: "RAMPURA",
    63: "KOHAT ENCLAVE",
    64: "SHAKUR PUR",
    65: "NIMRI COLONY",
    66: "SAWAN PARK",
    67: "WAJIRPUR",
    68: "ASHOK VIHAR",
    69: "KAMLA NAGAR",
    70: "RANA PRATAP BAGH",
    71: "SANGAM PARK",
    72: "MODEL TOWN",
    73: "SHASTRI NAGAR",
    74: "INDER LOK COLONY",
    75: "KISHAN GANJ",
    76: "DEPUTY GANJ",
    77: "KASHMERE GATE",
    78: "MAJNU KA TILA",
    79: "JAMA MASJID",
    80: "CHANDNI CHOWK",
    81: "MINTO ROAD",
    82: "KUCHA PANDIT",
    83: "BAZAR SITARAM",
    84: "TURKMAN GATE",
    85: "IDGAH ROAD",
    86: "BALLIMARAN",
    87: "RAM NAGAR",
    88: "QASABPURA",
    89: "PAHAR GANJ",
    90: "MODEL BASTI",
    91: "KAROL BAGH",
    92: "DEV NAGAR",
    93: "BALJIT NAGAR",
    94: "WEST PATEL NAGAR",
    95: "EAST PATEL NAGAR",
    96: "NEW RANJIT NAGAR",
    97: "KIRTI NAGAR",
    98: "MANSAROWER GARDEN",
    99: "MOTI NAGAR",
    100: "KARAM PURA",
    101: "RAJA GARDEN",
    102: "RAGHUBIR NAGAR",
    103: "PUNJABI BAGH",
    104: "MADIPUR",
    105: "RAJOURI GARDEN",
    106: "TAGORE GARDEN",
    107: "VISHNU GARDEN",
    108: "KHYALA",
    109: "JANAK PURI NORTH",
    110: "NANGAL RAYA",
    111: "HARI NAGAR",
    112: "SUBHASH NAGAR",
    113: "MAHAVIR NAGAR",
    114: "TILAK NAGAR",
    115: "MAJOR BHUPINDAR SINGH NAGAR",
    116: "VIKASPURI EAST",
    117: "JANAK PURI WEST",
    118: "JANAK PURI SOUTH",
    119: "MILAP NAGAR",
    120: "SITA PURI",
    121: "KUNWAR SINGH NAGAR",
    122: "HASTSAL",
    123: "VIKAS PURI",
    124: "VIKAS NAGAR",
    125: "MOHAN GARDEN",
    126: "NAWADA",
    127: "UTTAM NAGAR",
    128: "BINDAPUR",
    129: "DABRI",
    130: "MANGLAPURI",
    131: "SAGARPUR",
    132: "SAGARPUR WEST",
    133: "CHHAWLA",
    134: "NANGLI SAKRAVATI",
    135: "KAKRAULA",
    136: "MATIALA",
    137: "ROSHANPURA",
    138: "NAJAFGARH",
    139: "DICHAON KALAN",
    140: "KHERA",
    141: "BIJWASAN",
    142: "RAJ NAGAR",
    143: "KAPASHERA",
    144: "MAHIPALPUR",
    145: "PALAM",
    146: "SADH NAGAR",
    147: "MAHAVIR ENCLAVE",
    148: "MADHU VIHAR",
    149: "RAJENDER NAGAR",
    150: "PUSA",
    151: "INDER PURI",
    152: "NARAINA",
    153: "DARYAGANJ",
    154: "NIZAMUDDIN",
    155: "LAJPAT NAGAR",
    156: "BHOGAL",
    157: "KASTURBA NAGAR",
    158: "KOTLA MUBARAKPUR",
    159: "ANDREWSGANJ",
    160: "AMAR COLONY",
    161: "MALVIYA NAGAR",
    162: "HAUZ RANI",
    163: "SAFDARJANG ENCLAVE",
    164: "HAUZ KHAS",
    165: "VASANT VIHAR",
    166: "MUNIRKA",
    167: "R.K. PURAM",
    168: "NANAK PURA",
    169: "LADOSARAI",
    170: "MEHRAULI",
    171: "VASANTKUNJ",
    172: "KISHANGARH",
    173: "DEOLI",
    174: "CHHATARPUR",
    175: "AYA NAGAR",
    176: "BHATI",
    177: "SAID UL AJAIB",
    178: "SANGAM VIHAR",
    179: "TIGRI",
    180: "DAKSHINPURI EXT.",
    181: "KHANPUR",
    182: "AMBEDKAR NAGAR",
    183: "MADANGIR",
    184: "PUSHP VIHAR",
    185: "TUGHLAKABAD EXTN",
    186: "SANGAM VIHAR WEST",
    187: "SANGAM VIHAR CENTRAL",
    188: "SANGAM VIHAR EAST",
    189: "CHIRAG DELHI",
    190: "CHITRANJAN PARK",
    191: "SHAPUR JAT",
    192: "GREATER KAILASH-I",
    193: "SRI NIWASPURI",
    194: "EAST OF KAILASH",
    195: "GOVIND PURI",
    196: "KALKAJI",
    197: "TUGHLAKABAD",
    198: "PUL PEHLAD",
    199: "TEKHAND",
    200: "HARKESH NAGAR",
    201: "JAITPUR",
    202: "MEETHEYPUR",
    203: "BADAR PUR",
    204: "MOLARBAND",
    205: "ZAKIR NAGAR",
    206: "OKHLA",
    207: "MADANPUR KHADAR",
    208: "SARITA VIHAR",
    209: "MAYUR VIHAR PHASE-I",
    210: "DALLOPURA",
    211: "TRILOK PURI",
    212: "NEW ASHOK NAGAR",
    213: "KALYAN PURI",
    214: "KHICHRIPUR",
    215: "KONDLI",
    216: "GHAROLI",
    217: "VINOD NAGAR",
    218: "MANDAWALI",
    219: "MAYUR VIHAR PHASE II",
    220: "PATPARGANJ",
    221: "KISHAN KUNJ",
    222: "LAXMI NAGAR",
    223: "SHAKARPUR",
    224: "PANDAV NAGAR",
    225: "ANAND VIHAR",
    226: "VISHWASH NAGAR",
    227: "I.P. EXTENSION",
    228: "PREET VIHAR",
    229: "KRISHNA NAGAR",
    230: "GEETA COLONY",
    231: "GHONDLI",
    232: "ANARKALI",
    233: "DHARAMPURA",
    234: "GANDHI NAGAR",
    235: "AZAD NAGAR",
    236: "RAGHUBAR PURA",
    237: "SHAHDARA",
    238: "JHILMIL",
    239: "VIVEK VIHAR",
    240: "DILSHAD COLONY",
    241: "DILSHAD GARDEN",
    242: "NEW SEEMA PURI",
    243: "NAND NAGRI",
    244: "SUNDER NAGARI",
    245: "DURGA PURI",
    246: "ASHOK NAGAR",
    247: "RAM NAGAR",
    248: "WELCOME COLONY",
    249: "CHAUHAN BANGER",
    250: "ZAFFRABAD",
    251: "NEW USMANPUR",
    252: "MAUJPUR",
    253: "BHAJANPURA",
    254: "BRAHAM PURI",
    255: "GHONDA",
    256: "YAMUNA VIHAR",
    257: "SUBHASH MOHALLA",
    258: "KARDAM PURI",
    259: "JANTA COLONY",
    260: "BABAR PUR",
    261: "JIWANPUR",
    262: "GOKALPUR",
    263: "SABOLI",
    264: "HARSH VIHAR",
    265: "SHIV VIHAR",
    266: "KARAWAL NAGAR EAST",
    267: "NEHRU VIHAR",
    268: "MUSTAFABAD",
    269: "KHAJOORI KHAS",
    270: "TUKHMIR PUR",
    271: "KARAWAL NAGAR WEST",
    272: "SONIA VIHAR",
}


def upgrade() -> None:
    # Build a single VALUES list for a bulk UPDATE
    cases = "\n".join(
        f"    WHEN number = {num} THEN '{name.replace(chr(39), chr(39)+chr(39))}'"
        for num, name in WARD_NAMES.items()
    )
    op.execute(f"""
        UPDATE wards
        SET name = CASE
{cases}
            ELSE name
        END
        WHERE number BETWEEN 1 AND 272
    """)

    # Refresh the materialized view so the API immediately returns real names
    op.execute("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_ward_stats")


def downgrade() -> None:
    op.execute("""
        UPDATE wards
        SET name = 'Ward ' || number::text
        WHERE number BETWEEN 1 AND 272
    """)
    op.execute("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_ward_stats")
